### ISSUE TITLE
Checklist for TagUI Python package

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#1]
- [x] python package project skeleton
- [x] invoking, controlling, closing tagui
- [x] compatibility with python 2 and 3
- [x] conversion to tagui python module
>
- [x] implement basic tagui steps - https://github.com/kelaberetiv/TagUI#steps-description
  - [x] http(s)
  - [x] click
  - [x] rclick
  - [x] dclick
  - [x] hover
  - [x] type
  - [x] select
  - [x] read
  - [x] show
  - [x] save
  - [x] snap
  - [x] load
  - [x] echo
  - [x] dump
  - [x] write
  - [x] ask
>
- [x] implement pro tagui steps - https://github.com/kelaberetiv/TagUI#steps-description
  - [x] keyboard
  - [x] mouse
  - [x] table
  - [x] wait
  - [x] check
  - [x] upload
  - [x] download
  - [x] api
  - [x] run
  - [x] dom
  - [x] vision
  - [x] timeout
>
- [x] implement tagui helper functions - https://github.com/kelaberetiv/TagUI#helper-functions
  - [x] present()
  - [x] visible()
  - [x] count()
  - [x] url()
  - [x] title()
  - [x] text()
  - [x] timer()
  - [x] mouse_xy()
  - [x] mouse_x()
  - [x] mouse_y()
>
- [x] address known and potential issues
  - [x] send single quote in text string input
  - [x] echo with correct quotes in tagui log
  - [x] parameter to invoke visual automation
  - [x] accept (x,y) coordinates as parameters
  - [x] validate sending of backslash correctly
  - [x] validate path for filename parameters
  - [x] auto sikulix jython 1st-run integration
>
- [x] pre-release iteration, testing and docs
  - [x] review, iterate, refine features list
  - [x] auto download + setup + test tagui
  - [x] test usage with python 2 and 3 envs
  - [x] test usage python interactive mode
  - [x] test usage with mac, windows, linux
  - [x] test usage with jupyter notebook
  - [x] test, validate, tune all functions
  - [x] github and pypi documentation
>
- [x] announce and start distribution
